var variable1, variable2, variable3;
var legalVariable1;
var myVariable;
var $name;
var _count;
var first_name;
document.write("<h1>Rules for naming JS variables</h1>");
document.write("Variable names can only contain letters, digits, underscores, and dollar signs. For example: $my_1stVariable<br>");
document.write("Variables must begin with a letter, underscore, or dollar sign. For example: $name, _name, or name<br>");
document.write("Variable names are case-sensitive<br>");
document.write("Variable names should not be JavaScript keywords");
